# Config for Spiral Dataset
class: UnrealDataset
basedir: /home/shared_ws6/data/unreal_engine
agent: rover_0  # Default, script will iterate over all
cameras: ["front"]
measurements: ["front"] # For backward compatibility
preload: none
euroc_format: true
data_types: ["rgb", "depth"]
